Updating recipes

diff --git a/recipes/meta/codeblocks/Recipe b/recipes/meta/codeblocks/Recipe
--- a/recipes/meta/codeblocks/Recipe
+++ b/recipes/meta/codeblocks/Recipe
@@ -2,6 +2,7 @@
 
 # Halt on errors
 set -e
+set -x
 
 # Check dependencies
 which wget >/dev/null 2>&1 || ( echo wget missing && exit 1 )
@@ -13,7 +14,7 @@ which dpkg-scanpackages  >/dev/null 2>&1 || ( echo dpkg-scanpackages missing && 
 # If the yaml file doesn't exist locally, get it from GitHub
 if [ ! -f "$1" ] ; then
   YAMLFILE=/tmp/_recipe.yml
-  wget -q "https://github.com/probonopd/AppImages/raw/master/recipes/meta/$1.yml" -O "$YAMLFILE"
+  wget -q "https://github.com/fusion809/AppImages/raw/master/recipes/meta/$1/$1.yml" -O "$YAMLFILE"
 else
   YAMLFILE=$(readlink -f $1)
 fi
@@ -102,6 +103,21 @@ fi
 if [ ! -z "${_ingredients_dist}" ] ; then
   rm status 2>/dev/null || true
   generate_status
+
+  # Some packages depend on an exact version of a dependency to be installed.
+  # Use
+  # ingredients:
+  #   pretend:
+  #     - packagename version_to_be_pretended
+  if [ ! -z "${_ingredients_pretend[0]}" ] ; then
+    for PRETEND in "${_ingredients_pretend[@]}" ; do
+      P_PKG=$(echo "$PRETEND" | cut -d " " -f 1)
+      P_VER=$(echo "$PRETEND" | cut -d " " -f 2)
+      cat status | tr '\n' '@' | sed -e 's|@@|\n\n|g' | sed -e 's|Package: '"$P_PKG"'@Status: install ok installed@Architecture: all@Version: 9:999.999.999|Package: '"$P_PKG"'@Status: install ok installed@Architecture: all@Version: '"$P_VER"'|g' | sed -e 's|@|\n|g' > status.temp
+      mv status.temp status
+    done
+  fi
+
   if [ -e sources.list ] ; then
     rm sources.list
   fi
@@ -139,8 +155,13 @@ if [ ! -z "${_ingredients_dist}" ] ; then
     INSTALL="${_ingredients_package}"
   fi
 
+  # If packages are specifically listed, only install these, not a package with the name of the app
+  if [ ! -z "${_ingredients_packages[0]}" ] ; then
+    INSTALL=${_ingredients_packages[@]}
+  fi
+
   apt-get $OPTIONS update || true
-  URLS=$(apt-get $OPTIONS -y install --print-uris "$INSTALL" ${_ingredients_packages[@]} | cut -d "'" -f 2 | grep -e "^http")
+  URLS=$(apt-get $OPTIONS -y install --print-uris $INSTALL | cut -d "'" -f 2 | grep -e "^http")
   for URL in $URLS ; do
     if [ ! -f $(basename "$URL") ] ; then
       wget -c $URL
@@ -166,7 +187,28 @@ find . -path *icons* -path *256* -name "*$LOWERAPP*" -exec cp {} usr/share/icons
 find . -path *icons* -path *512* -name "*$LOWERAPP*" -exec cp {} usr/share/icons/hicolor/512x512/apps/ \; || true
 
 get_icon
-get_apprun
+
+if [ -z "${_union}" ] ; then
+  get_apprun
+else
+cat > AppRun <<\EOF
+#!/bin/sh
+HERE="$(dirname "$(readlink -f "${0}")")"
+export UNION_PRELOAD="${HERE}"
+export LD_PRELOAD="${HERE}/libunionpreload.so"
+export PATH="${HERE}"/usr/bin/:"${HERE}"/usr/sbin/:"${HERE}"/usr/games/:"${HERE}"/bin/:"${HERE}"/sbin/:"${PATH}"
+export LD_LIBRARY_PATH="${HERE}"/usr/lib/:"${HERE}"/usr/lib/i386-linux-gnu/:"${HERE}"/usr/lib/x86_64-linux-gnu/:"${HERE}"/usr/lib32/:"${HERE}"/usr/lib64/:"${HERE}"/lib/:"${HERE}"/lib/i386-linux-gnu/:"${HERE}"/lib/x86_64-linux-gnu/:"${HERE}"/lib32/:"${HERE}"/lib64/:"${LD_LIBRARY_PATH}"
+export PYTHONPATH="${HERE}"/usr/share/pyshared/:"${PYTHONPATH}"
+export XDG_DATA_DIRS="${HERE}"/usr/share/:"${XDG_DATA_DIRS}"
+export PERLLIB="${HERE}"/usr/share/perl5/:"${HERE}"/usr/lib/perl5/:"${PERLLIB}"
+export GSETTINGS_SCHEMA_DIR="${HERE}"/usr/share/glib-2.0/schemas/:"${GSETTINGS_SCHEMA_DIR}"
+export QT_PLUGIN_PATH="${HERE}"/usr/lib/qt4/plugins/:"${HERE}"/usr/lib/i386-linux-gnu/qt4/plugins/:"${HERE}"/usr/lib/x86_64-linux-gnu/qt4/plugins/:"${HERE}"/usr/lib32/qt4/plugins/:"${HERE}"/usr/lib64/qt4/plugins/:"${HERE}"/usr/lib/qt5/plugins/:"${HERE}"/usr/lib/i386-linux-gnu/qt5/plugins/:"${HERE}"/usr/lib/x86_64-linux-gnu/qt5/plugins/:"${HERE}"/usr/lib32/qt5/plugins/:"${HERE}"/usr/lib64/qt5/plugins/:"${QT_PLUGIN_PATH}"
+EXEC=$(grep -e '^Exec=.*' "${HERE}"/*.desktop | head -n 1 | cut -d "=" -f 2 | cut -d " " -f 1)
+exec "${EXEC}" $@
+EOF
+chmod a+x AppRun
+fi
+
 get_desktop
 
 # Prevent Qt from loading plugins from the system
@@ -194,6 +236,18 @@ if [ ! -z "${_script}" ] ; then
   shell_execute $YAMLFILE _script
 fi
 
+# Some non-distribution provided applications have an absolute
+# path in the Exec= line which we remove for relocateability
+DESKTOP=$(find . -name '*.desktop' | head -n 1)
+if [ -z "$DESKTOP" ] ; then
+  echo "desktop file not found, aborting"
+  exit 1
+else
+  ORIG=$(grep -o "^Exec=.*$" "${DESKTOP}" | head -n 1| cut -d " " -f 1)
+  REPL=$(basename $(grep -o "^Exec=.*$" "${DESKTOP}" | head -n 1 | cut -d " " -f 1 | sed -e 's|Exec=||g'))
+  sed -i -e 's|'"${ORIG}"'|Exec='"${REPL}"'|g' "${DESKTOP}"
+fi
+
 # Compile GLib schemas if the subdirectory is present in the AppImage
 # AppRun has to export GSETTINGS_SCHEMA_DIR for this to work
 if [ -d usr/share/glib-2.0/schemas/ ] ; then
@@ -211,6 +265,16 @@ fi
 if [ ! -z "${_binpatch}" ] ; then
   find usr/ -type f -exec sed -i -e 's|/usr|././|g' {} \;
   find usr/ -type f -exec sed -i -e 's@././/bin/env@/usr/bin/env@g' {} \;
+fi
+
+# Don't suffer from NIH; use LD_PRELOAD to override calls to /usr paths
+if [ ! -z "${_union}" ] ; then
+  mkdir -p usr/src/
+  wget -q "https://raw.githubusercontent.com/mikix/deb2snap/master/src/preload.c" -O - | \
+  sed -e 's|SNAPPY|UNION|g' | sed -e 's|SNAPP|UNION|g' | sed  -e 's|SNAP|UNION|g' | \
+  sed -e 's|snappy|union|g' > usr/src/libunionpreload.c
+  gcc -shared -fPIC usr/src/libunionpreload.c -o libunionpreload.so -ldl -DUNION_LIBNAME=\"libunionpreload.so\"
+  strip libunionpreload.so
 fi
 
 delete_blacklisted
